import type { Vulnerability } from "./types"

export const mockVulnerabilities: Vulnerability[] = [
  {
    id: "vuln-001",
    cveId: "CVE-2023-1234",
    description:
      "Remote code execution vulnerability in authentication module allows attackers to execute arbitrary code via crafted requests.",
    severity: "Critical",
    vendor: "Microsoft",
    hasPatch: true,
    patchId: "MS23-012",
    patchVersion: "1.2.3",
    patchReleaseDate: "2023-04-15",
    affectedSystems: ["Windows Server 2019", "Windows 10", "Windows 11"],
    cvssScore: 9.8,
    discoveryDate: "2023-03-10",
  },
  {
    id: "vuln-002",
    cveId: "CVE-2023-5678",
    description: "SQL injection vulnerability in database connector allows attackers to access unauthorized data.",
    severity: "High",
    vendor: "Oracle",
    hasPatch: true,
    patchId: "ORA-2023-02",
    patchVersion: "4.5.1",
    patchReleaseDate: "2023-05-22",
    affectedSystems: ["Oracle Database 19c", "Oracle Database 21c"],
    cvssScore: 8.5,
    discoveryDate: "2023-04-18",
  },
  {
    id: "vuln-003",
    cveId: "CVE-2023-9012",
    description: "Cross-site scripting vulnerability in web interface allows attackers to inject malicious scripts.",
    severity: "Medium",
    vendor: "Apache",
    hasPatch: false,
    affectedSystems: ["Apache HTTP Server 2.4.x"],
    cvssScore: 6.1,
    discoveryDate: "2023-05-05",
  },
  {
    id: "vuln-004",
    cveId: "CVE-2023-3456",
    description: "Buffer overflow vulnerability in network stack allows denial of service attacks.",
    severity: "High",
    vendor: "Cisco",
    hasPatch: true,
    patchId: "CSCO-SA-20230610",
    patchVersion: "2.1.0",
    patchReleaseDate: "2023-06-10",
    affectedSystems: ["Cisco IOS XE", "Cisco IOS XR"],
  },
  {
    id: "vuln-005",
    cveId: "CVE-2023-7890",
    description: "Authentication bypass vulnerability allows unauthorized access to admin console.",
    severity: "Critical",
    vendor: "VMware",
    hasPatch: false,
    affectedSystems: ["VMware vCenter Server", "VMware ESXi"],
  },
  {
    id: "vuln-006",
    cveId: "CVE-2023-2345",
    description: "Information disclosure vulnerability exposes sensitive configuration data.",
    severity: "Medium",
    vendor: "IBM",
    hasPatch: true,
    patchId: "IBM-SV-2023-07",
    patchVersion: "3.0.1",
    patchReleaseDate: "2023-07-05",
    affectedSystems: ["IBM WebSphere", "IBM DB2"],
  },
  {
    id: "vuln-007",
    cveId: "CVE-2023-6789",
    description: "Privilege escalation vulnerability allows local users to gain root access.",
    severity: "High",
    vendor: "Red Hat",
    hasPatch: true,
    patchId: "RHSA-2023:2456",
    patchVersion: "5.1.2",
    patchReleaseDate: "2023-08-12",
    affectedSystems: ["Red Hat Enterprise Linux 8", "Red Hat Enterprise Linux 9"],
  },
  {
    id: "vuln-008",
    cveId: "CVE-2023-0123",
    description: "Path traversal vulnerability allows access to files outside the web root.",
    severity: "Medium",
    vendor: "Nginx",
    hasPatch: false,
    affectedSystems: ["Nginx 1.20.x", "Nginx 1.21.x"],
  },
  {
    id: "vuln-009",
    cveId: "CVE-2023-4567",
    description: "Insecure deserialization vulnerability allows remote code execution.",
    severity: "Critical",
    vendor: "Adobe",
    hasPatch: true,
    patchId: "APSB23-45",
    patchVersion: "2023.4.1",
    patchReleaseDate: "2023-09-05",
    affectedSystems: ["Adobe Acrobat", "Adobe Reader"],
  },
  {
    id: "vuln-010",
    cveId: "CVE-2023-8901",
    description: "Memory corruption vulnerability in browser engine allows arbitrary code execution.",
    severity: "Critical",
    vendor: "Google",
    hasPatch: true,
    patchId: "GOOG-2023-1015",
    patchVersion: "115.0.5790.102",
    patchReleaseDate: "2023-10-15",
    affectedSystems: ["Chrome", "Chromium-based browsers"],
  },
  {
    id: "vuln-011",
    cveId: "CVE-2023-2468",
    description: "Server-side request forgery vulnerability allows internal network scanning.",
    severity: "High",
    vendor: "Amazon",
    hasPatch: false,
    affectedSystems: ["AWS Lambda", "Amazon EC2"],
  },
  {
    id: "vuln-012",
    cveId: "CVE-2023-3579",
    description: "XML external entity injection vulnerability allows file disclosure.",
    severity: "Medium",
    vendor: "SAP",
    hasPatch: true,
    patchId: "SAP-SV-2023-011",
    patchVersion: "7.2.3",
    patchReleaseDate: "2023-11-08",
    affectedSystems: ["SAP NetWeaver", "SAP HANA"],
  },
  {
    id: "vuln-013",
    cveId: "CVE-2023-9876",
    description: "Cryptographic weakness in TLS implementation allows man-in-the-middle attacks.",
    severity: "High",
    vendor: "OpenSSL",
    hasPatch: true,
    patchId: "OPENSSL-2023-12",
    patchVersion: "3.1.4",
    patchReleaseDate: "2023-12-01",
    affectedSystems: ["OpenSSL 3.0.x", "OpenSSL 3.1.x"],
  },
  {
    id: "vuln-014",
    cveId: "CVE-2023-1357",
    description: "Race condition in file handling allows unauthorized file access.",
    severity: "Low",
    vendor: "Linux",
    hasPatch: false,
    affectedSystems: ["Linux Kernel 5.15.x", "Linux Kernel 6.0.x"],
  },
  {
    id: "vuln-015",
    cveId: "CVE-2023-2468",
    description: "Command injection vulnerability in admin interface allows remote code execution.",
    severity: "Critical",
    vendor: "Juniper",
    hasPatch: true,
    patchId: "JSA-2023-09",
    patchVersion: "22.3R1",
    patchReleaseDate: "2023-09-20",
    affectedSystems: ["Juniper Junos OS", "Juniper SRX Series"],
  },
  {
    id: "vuln-016",
    cveId: "CVE-2023-5792",
    description: "Broken access control vulnerability allows unauthorized data modification.",
    severity: "Medium",
    vendor: "Salesforce",
    hasPatch: true,
    patchId: "SFDC-SV-2023-05",
    patchVersion: "Winter '23",
    patchReleaseDate: "2023-10-10",
    affectedSystems: ["Salesforce CRM", "Salesforce Commerce Cloud"],
  },
  {
    id: "vuln-017",
    cveId: "CVE-2023-7531",
    description: "Insecure direct object reference vulnerability exposes sensitive user data.",
    severity: "High",
    vendor: "WordPress",
    hasPatch: false,
    affectedSystems: ["WordPress 6.1.x", "WordPress 6.2.x"],
  },
  {
    id: "vuln-018",
    cveId: "CVE-2023-0987",
    description: "Use-after-free vulnerability in memory management allows arbitrary code execution.",
    severity: "Critical",
    vendor: "Mozilla",
    hasPatch: true,
    patchId: "MFSA2023-42",
    patchVersion: "115.3.1",
    patchReleaseDate: "2023-11-15",
    affectedSystems: ["Firefox", "Firefox ESR"],
  },
  {
    id: "vuln-019",
    cveId: "CVE-2023-3210",
    description: "Improper certificate validation allows SSL/TLS spoofing attacks.",
    severity: "High",
    vendor: "Apple",
    hasPatch: true,
    patchId: "APPLE-SA-2023-10-25",
    patchVersion: "17.1",
    patchReleaseDate: "2023-10-25",
    affectedSystems: ["iOS", "macOS"],
  },
  {
    id: "vuln-020",
    cveId: "CVE-2023-6543",
    description: "Uncontrolled resource consumption vulnerability allows denial of service attacks.",
    severity: "Low",
    vendor: "Python",
    hasPatch: false,
    affectedSystems: ["Python 3.10.x", "Python 3.11.x"],
  },
  {
    id: "vuln-021",
    cveId: "CVE-2023-8765",
    description: "Server-side template injection vulnerability allows remote code execution.",
    severity: "Critical",
    vendor: "Jenkins",
    hasPatch: true,
    patchId: "SECURITY-2023-11",
    patchVersion: "2.414.1",
    patchReleaseDate: "2023-11-29",
    affectedSystems: ["Jenkins LTS", "Jenkins Weekly"],
  },
  {
    id: "vuln-022",
    cveId: "CVE-2023-4321",
    description: "Improper input validation allows cross-site request forgery attacks.",
    severity: "Medium",
    vendor: "Drupal",
    hasPatch: true,
    patchId: "SA-CORE-2023-005",
    patchVersion: "10.1.2",
    patchReleaseDate: "2023-08-15",
    affectedSystems: ["Drupal 9.x", "Drupal 10.x"],
  },
  {
    id: "vuln-023",
    cveId: "CVE-2023-9870",
    description: "Weak password hashing implementation allows offline password cracking.",
    severity: "High",
    vendor: "HashiCorp",
    hasPatch: false,
    affectedSystems: ["Vault", "Terraform"],
  },
  {
    id: "vuln-024",
    cveId: "CVE-2023-1122",
    description: "Improper authentication vulnerability allows session hijacking.",
    severity: "High",
    vendor: "Dell",
    hasPatch: true,
    patchId: "DSA-2023-123",
    patchVersion: "5.2.1",
    patchReleaseDate: "2023-07-18",
    affectedSystems: ["Dell EMC PowerEdge", "Dell EMC PowerStore"],
  },
  {
    id: "vuln-025",
    cveId: "CVE-2023-5544",
    description: "Integer overflow vulnerability in image processing allows arbitrary code execution.",
    severity: "Medium",
    vendor: "NVIDIA",
    hasPatch: true,
    patchId: "NVIDIA-SA-2023-0010",
    patchVersion: "535.104.05",
    patchReleaseDate: "2023-09-30",
    affectedSystems: ["NVIDIA GPU Drivers", "NVIDIA CUDA"],
  },
]
